language: php
php:
  - "hhvm"
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
script:
  - composer test
notifications:
  email: false
