language: generic
sudo: required
dist: trusty
before_install:
  - sudo apt-get install software-properties-common
  - sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449
  - sudo add-apt-repository "deb http://dl.hhvm.com/ubuntu $(lsb_release -sc) main"
  - sudo apt-get update
  - curl -sS https://getcomposer.org/installer | php
  - sudo mv composer.phar /usr/local/bin/composer
install:
  - sudo apt-get install hhvm
before_script:
  - travis_retry composer install --no-interaction
  - touch .hhconfig
script:
  - composer check
  - killall hh_server
  - composer test
matrix:
  fast_finish: true
notifications:
  email: false
