version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: export environment variables
          command: printenv | awk -F= '{if ($1 ~ /^(CI|GITHUB)/) print $1"="$2}' > .env
      - run:
          name: build docker images
          command: docker-compose build web
      - run:
          name: typecheck by typesafety-cli
          command: docker-compose run web typesafety --review
      - run:
          name: test
          command: docker-compose run web composer test
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: github
